/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import concessionaria.pessoas.ListaVendedores;
import concessionaria.pessoas.Vendedor;

/**
 *
 * @author ricardolima
 */
public class AlterarVendedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarCliente
     */
    public AlterarVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpVendedorNome = new javax.swing.JTextField();
        lblVendedorNome = new javax.swing.JLabel();
        lblVendedorCPF = new javax.swing.JLabel();
        inpVendedorCpf = new javax.swing.JTextField();
        lblVendedorRg = new javax.swing.JLabel();
        inpVendedorRg = new javax.swing.JTextField();
        inpVendedorNascimento = new javax.swing.JTextField();
        lblVendedorNascimento = new javax.swing.JLabel();
        btnVendedorAlterar = new javax.swing.JButton();
        inpVendedorEndereco = new javax.swing.JTextField();
        lblVendedorendereco = new javax.swing.JLabel();
        inpVendedorSalario = new javax.swing.JTextField();
        lblVendedorRg1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Alterar Cadastro vendedor");

        lblVendedorNome.setText("Nome");

        lblVendedorCPF.setText("CPF");

        lblVendedorRg.setText("RG");

        lblVendedorNascimento.setText("Data de Nascimento");

        btnVendedorAlterar.setText("Alterar");
        btnVendedorAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorAlterarActionPerformed(evt);
            }
        });

        lblVendedorendereco.setText("Endereço");

        lblVendedorRg1.setText("Salário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVendedorNome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inpVendedorNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpVendedorSalario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVendedorRg1)
                                        .addGap(0, 199, Short.MAX_VALUE)))
                                .addGap(351, 351, 351)
                                .addComponent(btnVendedorAlterar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpVendedorRg)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVendedorRg)
                                            .addComponent(lblVendedorendereco))
                                        .addGap(0, 168, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVendedorCPF)
                                    .addComponent(inpVendedorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVendedorNascimento)
                                    .addComponent(inpVendedorNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(inpVendedorEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVendedorNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpVendedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVendedorCPF)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVendedorRg)
                        .addComponent(lblVendedorNascimento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpVendedorRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpVendedorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpVendedorNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVendedorendereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpVendedorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnVendedorAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVendedorRg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpVendedorSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendedorAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorAlterarActionPerformed
        if(inpVendedorNome.getText().isEmpty()){
            Mensagem.erro("Falta inserir nome", "Falta dados");
        }else if(inpVendedorRg.getText().isEmpty()){
            Mensagem.erro("Falta inserir Rg", "Falta dados");
        }else if(inpVendedorCpf.getText().isEmpty()){
            Mensagem.erro("Falta inserir Cpf", "Falta dados");
        }else if(inpVendedorNascimento.getText().isEmpty()){
            Mensagem.erro("Falta inserir data de nascimento", "Falta dados");
        }else if(inpVendedorEndereco.getText().isEmpty()){
            Mensagem.erro("Falta inserir endereço", "Falta dados");
        }else if(inpVendedorSalario.getText().isEmpty()){
            Mensagem.erro("Falta inserir Salário", "Falta dados");
        }else{
            Vendedor novo = new Vendedor(inpVendedorNome.getText(), inpVendedorEndereco.getText(), inpVendedorRg.getText(), inpVendedorCpf.getText(), inpVendedorNascimento.getText(), Double.parseDouble(inpVendedorSalario.getText()));
            ListaVendedores.inserir(novo);
            ListaVendedores.remover(0);
        }
    }//GEN-LAST:event_btnVendedorAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVendedorAlterar;
    private javax.swing.JTextField inpVendedorCpf;
    private javax.swing.JTextField inpVendedorEndereco;
    private javax.swing.JTextField inpVendedorNascimento;
    private javax.swing.JTextField inpVendedorNome;
    private javax.swing.JTextField inpVendedorRg;
    private javax.swing.JTextField inpVendedorSalario;
    private javax.swing.JLabel lblVendedorCPF;
    private javax.swing.JLabel lblVendedorNascimento;
    private javax.swing.JLabel lblVendedorNome;
    private javax.swing.JLabel lblVendedorRg;
    private javax.swing.JLabel lblVendedorRg1;
    private javax.swing.JLabel lblVendedorendereco;
    // End of variables declaration//GEN-END:variables
}
