/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import concessionaria.produtos.ListaVeiculos;
import concessionaria.produtos.Moto;
import concessionaria.produtos.Veiculo;
import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ricardolima
 */
public class CadastrarMoto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarVeiculo
     */
    public CadastrarMoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpMotoFabricante = new javax.swing.JTextField();
        lblMotoFabricante = new javax.swing.JLabel();
        lblMotoModelo = new javax.swing.JLabel();
        inpMotoModelo = new javax.swing.JTextField();
        inpMotoAno = new javax.swing.JTextField();
        lblMotoAno = new javax.swing.JLabel();
        inpMotoCor = new javax.swing.JTextField();
        lblMotoCor = new javax.swing.JLabel();
        inpMotoValor = new javax.swing.JTextField();
        lblMotoValor = new javax.swing.JLabel();
        inpMotoEstoque = new javax.swing.JTextField();
        lblMotoEstoque = new javax.swing.JLabel();
        inpMotoCilindradas = new javax.swing.JTextField();
        lblMotoCilidradas = new javax.swing.JLabel();
        btnMotoCadastrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Moto");

        lblMotoFabricante.setText("Fabricante");

        lblMotoModelo.setText("Modelo");

        lblMotoAno.setText("Ano");

        lblMotoCor.setText("Cor");

        lblMotoValor.setText("Valor");

        lblMotoEstoque.setText("Estoque");

        lblMotoCilidradas.setText("Cilindradas");

        btnMotoCadastrar.setText("Cadastrar");
        btnMotoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inpMotoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMotoFabricante, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMotoModelo)
                            .addComponent(inpMotoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpMotoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMotoAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMotoCor)
                            .addComponent(inpMotoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpMotoCilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMotoCilidradas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpMotoValor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMotoValor)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMotoEstoque)
                            .addComponent(inpMotoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMotoCadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMotoModelo)
                            .addComponent(lblMotoAno)
                            .addComponent(lblMotoCor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpMotoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpMotoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpMotoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMotoFabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpMotoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotoValor)
                    .addComponent(lblMotoEstoque)
                    .addComponent(lblMotoCilidradas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpMotoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpMotoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpMotoCilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMotoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMotoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoCadastrarActionPerformed
        if (inpMotoFabricante.getText().isEmpty()) {
            Mensagem.erro("Falta inserir fabricante da moto", "Falta dados");
        } else if (inpMotoModelo.getText().isEmpty()) {
            Mensagem.erro("Falta inserir o modelo da moto", "Falta dados");
        } else if (inpMotoAno.getText().isEmpty()) {
            Mensagem.erro("Falta inserir o ano da moto", "Falta dados");
        } else if (inpMotoCor.getText().isEmpty()) {
            Mensagem.erro("Falta inserir a cor da moto", "Falta dados");
        } else if (inpMotoValor.getText().isEmpty()) {
            Mensagem.erro("Falta inserir o valor da moto", "Falta dados");
        } else if (inpMotoCilindradas.getText().isEmpty()) {
            Mensagem.erro("Falta inserir a quantidade de cilindradas da moto", "Falta dados");
        } else {
            try {
                double motoValor = Double.parseDouble(inpMotoValor.getText());
                int motoCilindradas = Integer.parseInt(inpMotoCilindradas.getText());
                int motoEstoque = 0;
                if (!inpMotoEstoque.getText().isEmpty()){
                    motoEstoque = Integer.parseInt(inpMotoEstoque.getText());
                }
                Veiculo novo = new Moto(inpMotoFabricante.getText(), inpMotoModelo.getText(),
                        inpMotoAno.getText(), inpMotoCor.getText(), motoValor, motoCilindradas, motoEstoque);
                ListaVeiculos.inserir(novo);
                Mensagem.informacao("Moto Cadastrada com Sucesso", "Moto Cadastrada");
                for (Component C : this.getContentPane().getComponents()) {
                    if (C instanceof JTextField) {

                        ((JTextComponent) C).setText(""); //abstract superclass
                    }
                }
            } catch (Exception e) {
                Mensagem.erro("Dados inválidos no campo valor ou cilindradas", "Dados Inválidos");
            }
        }
    }//GEN-LAST:event_btnMotoCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMotoCadastrar;
    private javax.swing.JTextField inpMotoAno;
    private javax.swing.JTextField inpMotoCilindradas;
    private javax.swing.JTextField inpMotoCor;
    private javax.swing.JTextField inpMotoEstoque;
    private javax.swing.JTextField inpMotoFabricante;
    private javax.swing.JTextField inpMotoModelo;
    private javax.swing.JTextField inpMotoValor;
    private javax.swing.JLabel lblMotoAno;
    private javax.swing.JLabel lblMotoCilidradas;
    private javax.swing.JLabel lblMotoCor;
    private javax.swing.JLabel lblMotoEstoque;
    private javax.swing.JLabel lblMotoFabricante;
    private javax.swing.JLabel lblMotoModelo;
    private javax.swing.JLabel lblMotoValor;
    // End of variables declaration//GEN-END:variables
}
