/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import concessionaria.pessoas.Cliente;
import concessionaria.pessoas.ListaClientes;
import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ricardolima
 */
public class CadastrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpClienteNome = new javax.swing.JTextField();
        lblClienteNome = new javax.swing.JLabel();
        lblClienteCPF = new javax.swing.JLabel();
        inpClienteCpf = new javax.swing.JTextField();
        lblClienteRg = new javax.swing.JLabel();
        inpClienteRg = new javax.swing.JTextField();
        inpClienteNascimento = new javax.swing.JTextField();
        lblClienteNascimento = new javax.swing.JLabel();
        btnClientesCadastrar = new javax.swing.JButton();
        inpClienteEndereco = new javax.swing.JTextField();
        lblClienteendereco = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de clientes");

        lblClienteNome.setText("Nome");

        lblClienteCPF.setText("CPF");

        lblClienteRg.setText("RG");

        lblClienteNascimento.setText("Data de Nascimento");

        btnClientesCadastrar.setText("Cadastrar");
        btnClientesCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesCadastrarActionPerformed(evt);
            }
        });

        lblClienteendereco.setText("Endereço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClienteNome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inpClienteNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClientesCadastrar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpClienteRg)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblClienteRg)
                                            .addComponent(lblClienteendereco))
                                        .addGap(0, 168, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClienteCPF)
                                    .addComponent(inpClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClienteNascimento)
                                    .addComponent(inpClienteNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(inpClienteEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblClienteNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClienteCPF)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblClienteRg)
                        .addComponent(lblClienteNascimento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpClienteRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpClienteNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClienteendereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpClienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnClientesCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesCadastrarActionPerformed
        if (inpClienteNome.getText().isEmpty()) {
            Mensagem.erro("Falta inserir nome", "Falta dados");
        } else if (inpClienteRg.getText().isEmpty()) {
            Mensagem.erro("Falta inserir Rg", "Falta dados");
        } else if (inpClienteCpf.getText().isEmpty()) {
            Mensagem.erro("Falta inserir Cpf", "Falta dados");
        } else if (inpClienteNascimento.getText().isEmpty()) {
            Mensagem.erro("Falta inserir data de nascimento", "Falta dados");
        } else if (inpClienteEndereco.getText().isEmpty()) {
            Mensagem.erro("Falta inserir endereço", "Falta dados");
        } else {
            Cliente novo = new Cliente(inpClienteNome.getText(), inpClienteEndereco.getText(),
                    inpClienteRg.getText(), inpClienteCpf.getText(), inpClienteNascimento.getText());
            ListaClientes.inserir(novo);
            Mensagem.informacao("Cliente Cadastrado com Sucesso", "Cliente Cadastrado");
            for (Component C : this.getContentPane().getComponents()) {
                if (C instanceof JTextField) {

                    ((JTextComponent) C).setText(""); //abstract superclass
                }
            }
        }
    }//GEN-LAST:event_btnClientesCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesCadastrar;
    private javax.swing.JTextField inpClienteCpf;
    private javax.swing.JTextField inpClienteEndereco;
    private javax.swing.JTextField inpClienteNascimento;
    private javax.swing.JTextField inpClienteNome;
    private javax.swing.JTextField inpClienteRg;
    private javax.swing.JLabel lblClienteCPF;
    private javax.swing.JLabel lblClienteNascimento;
    private javax.swing.JLabel lblClienteNome;
    private javax.swing.JLabel lblClienteRg;
    private javax.swing.JLabel lblClienteendereco;
    // End of variables declaration//GEN-END:variables
}
