/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import concessionaria.produtos.Carro;
import concessionaria.produtos.ListaVeiculos;
import concessionaria.produtos.Veiculo;
import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ricardolima
 */
public class CadastrarCarro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarVeiculo
     */
    public CadastrarCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpCarroFabricante = new javax.swing.JTextField();
        lblCarroFabricante = new javax.swing.JLabel();
        lblCarroModelo = new javax.swing.JLabel();
        inpCarroModelo = new javax.swing.JTextField();
        inpCarroAno = new javax.swing.JTextField();
        lblCarroAno = new javax.swing.JLabel();
        inpCarroCor = new javax.swing.JTextField();
        lblCarroCor = new javax.swing.JLabel();
        inpCarroValor = new javax.swing.JTextField();
        lblCarroValor = new javax.swing.JLabel();
        inpCarroEstoque = new javax.swing.JTextField();
        lblCarroEstoque = new javax.swing.JLabel();
        inpCarroPortas = new javax.swing.JTextField();
        lblCarroPortas = new javax.swing.JLabel();
        btnCarroCadastrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Carro");
        setToolTipText("");

        lblCarroFabricante.setText("Fabricante");

        lblCarroModelo.setText("Modelo");

        lblCarroAno.setText("Ano");

        lblCarroCor.setText("Cor");

        lblCarroValor.setText("Valor");

        lblCarroEstoque.setText("Estoque");

        lblCarroPortas.setText("Portas");

        btnCarroCadastrar.setText("Cadastrar");
        btnCarroCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inpCarroFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarroFabricante, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarroModelo)
                            .addComponent(inpCarroModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpCarroAno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarroAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarroCor)
                            .addComponent(inpCarroCor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpCarroPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarroPortas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpCarroValor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarroValor)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarroEstoque)
                            .addComponent(inpCarroEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCarroCadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarroModelo)
                            .addComponent(lblCarroAno)
                            .addComponent(lblCarroCor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpCarroModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpCarroAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inpCarroCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarroFabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpCarroFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarroValor)
                    .addComponent(lblCarroEstoque)
                    .addComponent(lblCarroPortas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpCarroValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpCarroEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpCarroPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarroCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarroCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroCadastrarActionPerformed
        if (inpCarroFabricante.getText().isEmpty()) {
            Mensagem.erro("Falta inserir fabricante do carro", "Falta dados");
        } else if (inpCarroModelo.getText().isEmpty()) {
            Mensagem.erro("Falta inserir o modelo do carro", "Falta dados");
        } else if (inpCarroAno.getText().isEmpty()) {
            Mensagem.erro("Falta inserir o ano do carro", "Falta dados");
        } else if (inpCarroCor.getText().isEmpty()) {
            Mensagem.erro("Falta inserir a cor do carro", "Falta dados");
        } else if (inpCarroPortas.getText().isEmpty()) {
            Mensagem.erro("Falta inserir a quantidade de portas do carro", "Falta dados");
        } else if (inpCarroValor.getText().isEmpty()) {
            Mensagem.erro("Falta inserir o valor do carro", "Falta dados");
        } else {
            try {
                double carroValor = Double.parseDouble(inpCarroValor.getText());
                int carroPortas = Integer.parseInt(inpCarroPortas.getText());
                int carroEstoque = 0;
                if (!inpCarroEstoque.getText().isEmpty()) {
                    carroEstoque = Integer.parseInt(inpCarroEstoque.getText());
                } 
                Veiculo novo = new Carro(inpCarroFabricante.getText(), inpCarroModelo.getText(),
                            inpCarroAno.getText(), inpCarroCor.getText(), carroValor, carroEstoque, carroPortas);
                    ListaVeiculos.inserir(novo);
                    Mensagem.informacao("Carro Cadastrado com Sucesso", "Carro Cadastrado");
                for (Component C : this.getContentPane().getComponents()) {
                    if (C instanceof JTextField) {

                        ((JTextComponent) C).setText(""); //abstract superclass
                    }
                }
            } catch (Exception e) {
                Mensagem.erro("Dados inválidos no campo valor ou quantidade de portas", "Dados Inválidos");
            }
        }
    }//GEN-LAST:event_btnCarroCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarroCadastrar;
    private javax.swing.JTextField inpCarroAno;
    private javax.swing.JTextField inpCarroCor;
    private javax.swing.JTextField inpCarroEstoque;
    private javax.swing.JTextField inpCarroFabricante;
    private javax.swing.JTextField inpCarroModelo;
    private javax.swing.JTextField inpCarroPortas;
    private javax.swing.JTextField inpCarroValor;
    private javax.swing.JLabel lblCarroAno;
    private javax.swing.JLabel lblCarroCor;
    private javax.swing.JLabel lblCarroEstoque;
    private javax.swing.JLabel lblCarroFabricante;
    private javax.swing.JLabel lblCarroModelo;
    private javax.swing.JLabel lblCarroPortas;
    private javax.swing.JLabel lblCarroValor;
    // End of variables declaration//GEN-END:variables
}
