/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import concessionaria.pessoas.ListaClientes;
import concessionaria.pessoas.ListaVendedores;
import concessionaria.produtos.ListaVeiculos;
import concessionaria.vendas.ListaVendas;
import concessionaria.vendas.Venda;
import java.awt.Component;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ricardolima
 */
public class RealizarVenda extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form CadastrarVeiculo
     */
    public RealizarVenda() {
        initComponents();
    }

    public static void setCliente(int numero) {
        inpCliente.setText(Integer.toString(numero));
        String nome = ListaClientes.getCliente(numero).getNome();
        descCliente.setText(nome);
    }

    public static void setVendedor(int numero) {
        inpVendedor.setText(Integer.toString(numero));
        String nome = ListaVendedores.getVendedor(numero).getNome();
        descVendedor.setText(nome);
    }

    public static void setVeiculo(int numero) {
        inpVeiculo.setText(Integer.toString(numero));
        String nome = ListaVeiculos.getVeiculo(numero).getModelo();
        descVeiculo.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpVendedor = new javax.swing.JTextField();
        lblVendedorNome = new javax.swing.JLabel();
        lblClienteNome = new javax.swing.JLabel();
        inpCliente = new javax.swing.JTextField();
        inpVeiculo = new javax.swing.JTextField();
        lblVeiculo = new javax.swing.JLabel();
        descVendedor = new javax.swing.JTextField();
        descCliente = new javax.swing.JTextField();
        descVeiculo = new javax.swing.JTextField();
        inpVendaQuantidade = new javax.swing.JTextField();
        jbRealizarVenda = new javax.swing.JButton();
        inpVendaFormaPagamento = new javax.swing.JTextField();
        inpData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Realizar Venda");

        inpVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpVendedorActionPerformed(evt);
            }
        });

        lblVendedorNome.setText("Vendedor*");
        lblVendedorNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVendedorNomeMouseClicked(evt);
            }
        });

        lblClienteNome.setText("Cliente*");
        lblClienteNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClienteNomeMouseClicked(evt);
            }
        });

        inpCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpClienteActionPerformed(evt);
            }
        });

        inpVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpVeiculoActionPerformed(evt);
            }
        });

        lblVeiculo.setText("Veiculo*");
        lblVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVeiculoMouseClicked(evt);
            }
        });

        descVendedor.setEditable(false);

        descCliente.setEditable(false);

        descVeiculo.setEditable(false);

        jbRealizarVenda.setText("Realizar Venda");
        jbRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRealizarVendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Forma de Pagamento");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Data");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("*Clique no label para carregar os dados.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVendedorNome)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblClienteNome)
                                        .addComponent(inpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                        .addComponent(lblVeiculo)
                                        .addComponent(inpVeiculo)
                                        .addComponent(inpVendedor))
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descVendedor)
                            .addComponent(descVeiculo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descCliente)
                            .addComponent(inpVendaFormaPagamento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inpVendaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inpData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVendedorNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClienteNome)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(lblVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpVendaFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpVendaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbRealizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRealizarVendaActionPerformed
        if (inpVendedor.getText().isEmpty()) {
            Mensagem.erro("Digite o seu código", "Falta dados");
        } else if (inpCliente.getText().isEmpty()) {
            Mensagem.erro("Falta selecionar o cliente", "Falta dados");
        } else if (inpVeiculo.getText().isEmpty()) {
            Mensagem.erro("Falta Selecionar o veiculo", "Falta dados");
        } else if (inpVendaFormaPagamento.getText().isEmpty()) {
            Mensagem.erro("Falta informar a forma de Pagamento", "Falta dados");
        } else if (inpVendaQuantidade.getText().isEmpty()) {
            Mensagem.erro("Falta informar a quantidade da venda", "Falta dados");
        } else if (inpData.getText().isEmpty()) {
            Mensagem.erro("Falta inserir endereço", "Falta dados");
        } else {
            try {

                Venda nova = new Venda(Integer.parseInt(inpVeiculo.getText()),
                        Integer.parseInt(inpCliente.getText()),
                        Integer.parseInt(inpVendedor.getText()),
                        inpData.getText(),
                        inpVendaFormaPagamento.getText(),
                        Integer.parseInt(inpVendaQuantidade.getText()));
                ListaVendas.inserir(nova);
                Mensagem.informacao("Venda Realizada com Sucesso", "Venda Concretizada");
                for (Component C : this.getContentPane().getComponents()) {
                    if (C instanceof JTextField) {

                        ((JTextComponent) C).setText(""); //abstract superclass
                    }
                }
            } catch (Exception e) {
                Mensagem.erro("Dados inseridos inválidos", "Dados Inválidos" );
                System.out.println("Erro: " +e);
            }
        }
    }//GEN-LAST:event_jbRealizarVendaActionPerformed

    private void lblVendedorNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVendedorNomeMouseClicked
        try {
            Escolher.main(ListaVendedores.getLista(), 0);
            } catch (Exception e) {
            System.out.println("Erro: " + e);
        }
    }//GEN-LAST:event_lblVendedorNomeMouseClicked

    private void lblClienteNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClienteNomeMouseClicked
        try {
            Escolher.main(ListaClientes.getLista(), 1);
            } catch (Exception e) {
            System.out.println("Erro: " + e);
        }
    }//GEN-LAST:event_lblClienteNomeMouseClicked

    private void lblVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeiculoMouseClicked
        try {
            Escolher.main(ListaVeiculos.getLista(), 2);
            } catch (Exception e) {
            System.out.println("Erro: " + e);
        }
    }//GEN-LAST:event_lblVeiculoMouseClicked

    private void inpVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpVendedorActionPerformed
        try {
            int vendedorID = Integer.parseInt(inpVendedor.getText());
            String nome = ListaVendedores.getVendedor(vendedorID).getNome();
            descVendedor.setText(nome);
        } catch (Exception e) {
            Mensagem.erro("Vendedor não localizado", "Erro");
            System.out.println("Erro: " + e);
        }
    }//GEN-LAST:event_inpVendedorActionPerformed

    private void inpClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpClienteActionPerformed
        try {
            int clienteID = Integer.parseInt(inpCliente.getText());
            String cliente = ListaClientes.getCliente(clienteID).getNome();
            System.out.println(cliente);
            descCliente.setText(cliente);
        } catch (Exception e) {
            System.out.println("Erro: " + e);
            Mensagem.erro("Cliente não localizado", "Erro");
        }
    }//GEN-LAST:event_inpClienteActionPerformed

    private void inpVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpVeiculoActionPerformed
        try {
            int veiculoID = Integer.parseInt(inpVeiculo.getText());
            String veiculo = ListaVeiculos.getVeiculo(veiculoID).getModelo() + " | "
                    + ListaVeiculos.getVeiculo(veiculoID).getFabricante();
            descVeiculo.setText(veiculo);
        } catch (Exception e) {
            Mensagem.erro("Veiculo não localizado", "Erro");
            System.out.println("Erro: " + e);
        }
    }//GEN-LAST:event_inpVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField descCliente;
    private static javax.swing.JTextField descVeiculo;
    private static javax.swing.JTextField descVendedor;
    protected static javax.swing.JTextField inpCliente;
    private javax.swing.JTextField inpData;
    private static javax.swing.JTextField inpVeiculo;
    private javax.swing.JTextField inpVendaFormaPagamento;
    private javax.swing.JTextField inpVendaQuantidade;
    protected static javax.swing.JTextField inpVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbRealizarVenda;
    private javax.swing.JLabel lblClienteNome;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JLabel lblVendedorNome;
    // End of variables declaration//GEN-END:variables
}
