package DataChef;



import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.util.Arrays;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lucas
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    
    Comida c[] = new Comida[8];
    Bebida b[] = new Bebida[4];
    Acompanhamento a[] = new Acompanhamento[4];
    
    
    
    double total = 0;
    public String totalizacao(double x){
        total += x;
        DecimalFormat df = new DecimalFormat("0.00"); //converção para mostrar as casas decimais
        String saida = df.format(total);
        return saida;
    }
    
    
    
    public JanelaPrincipal() {
        initComponents();
         
        setIcon(); //chamada metodo que define icone do prog
        
        c[0] = new Comida ("Hambúrguer",7.00);
        c[1] = new Comida ("X-Burger",8.50);
        c[2] = new Comida ("X-Salada",10.00);
        c[3] = new Comida ("X-Tudo",15.00);
        c[4] = new Comida ("X-Filé",13.50);
        c[5] = new Comida ("Americano",15.00);
        c[6] = new Comida ("Filé Misto",15.00);
        c[7] = new Comida ("Hot- Dog",5.00);
        
        b[0] = new Bebida ("Refrigerante 250ml", 3.00);
        b[1] = new Bebida ("Refrigerante 500ml",2.50);
        b[2] = new Bebida ("Suco", 3.50);
        b[3] = new Bebida ("Água", 2.50);
        
        a[0] = new Acompanhamento ("Batata Frita P", 5.00);
        a[1] = new Acompanhamento ("Batata Frita G", 6.50);
        a[2] = new Acompanhamento ("Batata Frita c/ Cheddar", 8.00);
        a[3] = new Acompanhamento ("Chicken Fries", 7.50);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        BotaoSetaCima = new javax.swing.JButton();
        BotaoDeletar = new javax.swing.JButton();
        BotaoSetaBaixo = new javax.swing.JButton();
        Hambúrguer = new javax.swing.JButton();
        X_Filé = new javax.swing.JButton();
        Refrigerante_Lata250ml = new javax.swing.JButton();
        Batata_Frita_P = new javax.swing.JButton();
        X_Burguer = new javax.swing.JButton();
        Americano = new javax.swing.JButton();
        Refrigerante_Lata500ml = new javax.swing.JButton();
        Batata_Frita_G = new javax.swing.JButton();
        Hot_Dog = new javax.swing.JButton();
        Água = new javax.swing.JButton();
        Chicken_Fries = new javax.swing.JButton();
        X_Tudo = new javax.swing.JButton();
        Filé_Misto = new javax.swing.JButton();
        Suco = new javax.swing.JButton();
        Batata_Frita_c_Cheddar = new javax.swing.JButton();
        X_Salada = new javax.swing.JButton();
        BotaoDebito = new javax.swing.JButton();
        BotaoDinheiro = new javax.swing.JButton();
        BotaoCredito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Chef");
        setBackground(new java.awt.Color(179, 17, 2));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(179, 17, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));

        Tabela.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Valor individual", "Quantidade", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabela.setToolTipText("");
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(0).setPreferredWidth(200);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setResizable(false);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
        }

        BotaoSetaCima.setText("C");

        BotaoDeletar.setText("X");

        BotaoSetaBaixo.setText("B");

        Hambúrguer.setText("Hambúrguer");
        Hambúrguer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Hambúrguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HambúrguerActionPerformed(evt);
            }
        });

        X_Filé.setText("X- Filé");
        X_Filé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_FiléActionPerformed(evt);
            }
        });

        Refrigerante_Lata250ml.setText("Refrigerante Lata 250ml");
        Refrigerante_Lata250ml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refrigerante_Lata250mlActionPerformed(evt);
            }
        });

        Batata_Frita_P.setText("Batata Frita P");
        Batata_Frita_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batata_Frita_PActionPerformed(evt);
            }
        });

        X_Burguer.setText("X- Burguer");
        X_Burguer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_BurguerActionPerformed(evt);
            }
        });

        Americano.setText("Americano");
        Americano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanoActionPerformed(evt);
            }
        });

        Refrigerante_Lata500ml.setText("Refrigerante Lata 500ml");
        Refrigerante_Lata500ml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refrigerante_Lata500mlActionPerformed(evt);
            }
        });

        Batata_Frita_G.setText("Batata Frita G");
        Batata_Frita_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batata_Frita_GActionPerformed(evt);
            }
        });

        Hot_Dog.setText("Hot- Dog");
        Hot_Dog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hot_DogActionPerformed(evt);
            }
        });

        Água.setText("Água");
        Água.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÁguaActionPerformed(evt);
            }
        });

        Chicken_Fries.setText("Chicken Fries");
        Chicken_Fries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chicken_FriesActionPerformed(evt);
            }
        });

        X_Tudo.setText("X- Tudo");
        X_Tudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_TudoActionPerformed(evt);
            }
        });

        Filé_Misto.setText("Filé Misto");
        Filé_Misto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filé_MistoActionPerformed(evt);
            }
        });

        Suco.setText("Suco");
        Suco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucoActionPerformed(evt);
            }
        });

        Batata_Frita_c_Cheddar.setText("Batata Frita c/ Cheddar");
        Batata_Frita_c_Cheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batata_Frita_c_CheddarActionPerformed(evt);
            }
        });

        X_Salada.setText("X- Salada");
        X_Salada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_SaladaActionPerformed(evt);
            }
        });

        BotaoDebito.setText("Débito");
        BotaoDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDebitoActionPerformed(evt);
            }
        });

        BotaoDinheiro.setText("Dinheiro");
        BotaoDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDinheiroActionPerformed(evt);
            }
        });

        BotaoCredito.setText("Crédito");
        BotaoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCreditoActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAGAMENTO");

        jButton1.setText("Registros");

        jlTotal.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlTotal.setText("0,00");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("R$:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Hambúrguer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(X_Filé, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Refrigerante_Lata250ml, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Batata_Frita_P, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(X_Burguer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Americano, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Refrigerante_Lata500ml, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Batata_Frita_G, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(X_Salada, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Filé_Misto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Suco, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Batata_Frita_c_Cheddar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(X_Tudo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hot_Dog, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Água, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chicken_Fries, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(BotaoDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jlTotal))))
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotaoDeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoSetaCima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoSetaBaixo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hambúrguer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X_Filé, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refrigerante_Lata250ml, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batata_Frita_P, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(X_Burguer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Americano, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Refrigerante_Lata500ml, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Batata_Frita_G, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(X_Salada, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Filé_Misto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Suco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Batata_Frita_c_Cheddar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hot_Dog, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Água, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Chicken_Fries, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X_Tudo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotaoSetaCima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoDeletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotaoSetaBaixo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void X_SaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_SaladaActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { c[2].retornaNome(), c[2].retornaPreco(), q, (Double.parseDouble(q)*c[2].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[2].retornaPreco()));

    }//GEN-LAST:event_X_SaladaActionPerformed

    private void Batata_Frita_c_CheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batata_Frita_c_CheddarActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { a[2].retornaNome(), a[2].retornaPreco(), q, (Double.parseDouble(q)*a[2].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*a[2].retornaPreco()));

    }//GEN-LAST:event_Batata_Frita_c_CheddarActionPerformed

    private void SucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucoActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { b[2].retornaNome(), b[2].retornaPreco(), q, (Double.parseDouble(q)*b[2].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*b[2].retornaPreco()));

    }//GEN-LAST:event_SucoActionPerformed

    private void Filé_MistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filé_MistoActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { c[6].retornaNome(), c[6].retornaPreco(), q, (Double.parseDouble(q)*c[6].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[6].retornaPreco()));

    }//GEN-LAST:event_Filé_MistoActionPerformed

    private void X_TudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_TudoActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade?");

        Object[] row = { c[3].retornaNome(), c[3].retornaPreco(), q, (Double.parseDouble(q)*c[3].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[3].retornaPreco()));

    }//GEN-LAST:event_X_TudoActionPerformed

    private void Chicken_FriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chicken_FriesActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { a[3].retornaNome(), a[3].retornaPreco(), q, (Double.parseDouble(q)*a[3].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*a[3].retornaPreco()));

    }//GEN-LAST:event_Chicken_FriesActionPerformed

    private void ÁguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÁguaActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { b[3].retornaNome(), b[3].retornaPreco(), q, (Double.parseDouble(q)*b[3].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*b[3].retornaPreco()));

    }//GEN-LAST:event_ÁguaActionPerformed

    private void Hot_DogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hot_DogActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { c[7].retornaNome(), c[7].retornaPreco(), q, (Double.parseDouble(q)*c[7].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[7].retornaPreco()));

    }//GEN-LAST:event_Hot_DogActionPerformed

    private void Batata_Frita_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batata_Frita_GActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { a[1].retornaNome(), a[1].retornaPreco(), q, (Double.parseDouble(q)*a[1].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*a[1].retornaPreco()));

    }//GEN-LAST:event_Batata_Frita_GActionPerformed

    private void Refrigerante_Lata500mlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refrigerante_Lata500mlActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { b[1].retornaNome(), b[1].retornaPreco(), q, (Double.parseDouble(q)*b[1].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*b[1].retornaPreco()));

    }//GEN-LAST:event_Refrigerante_Lata500mlActionPerformed

    private void AmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanoActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { c[5].retornaNome(), c[5].retornaPreco(), q, (Double.parseDouble(q)*c[5].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[5].retornaPreco()));

    }//GEN-LAST:event_AmericanoActionPerformed

    private void X_BurguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_BurguerActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { c[1].retornaNome(), c[1].retornaPreco(), q, (Double.parseDouble(q)*c[1].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[1].retornaPreco()));

    }//GEN-LAST:event_X_BurguerActionPerformed

    private void Batata_Frita_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batata_Frita_PActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { a[0].retornaNome(), a[0].retornaPreco(), q, (Double.parseDouble(q)*a[0].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*a[0].retornaPreco()));

    }//GEN-LAST:event_Batata_Frita_PActionPerformed

    private void Refrigerante_Lata250mlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refrigerante_Lata250mlActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { b[0].retornaNome(), b[0].retornaPreco(), q, (Double.parseDouble(q)*b[0].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);
        
        jlTotal.setText(totalizacao(Double.parseDouble(q)*b[0].retornaPreco()));

    }//GEN-LAST:event_Refrigerante_Lata250mlActionPerformed

    private void X_FiléActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_FiléActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { c[4].retornaNome(), c[4].retornaPreco(), q, (Double.parseDouble(q)*c[4].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);

        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[4].retornaPreco()));

    }//GEN-LAST:event_X_FiléActionPerformed

    private void HambúrguerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HambúrguerActionPerformed

        String q;

        q = JOptionPane.showInputDialog("Qual é a quantidade? ");

        Object[] row = { c[0].retornaNome(), c[0].retornaPreco(), q, (Double.parseDouble(q)*c[0].retornaPreco())};
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();

        model.addRow(row);

        //total += (Double.parseDouble(q)*c[0].retornaPreco());
        //jlTotal.setText("" + total);

        jlTotal.setText(totalizacao(Double.parseDouble(q)*c[0].retornaPreco()));

    }//GEN-LAST:event_HambúrguerActionPerformed

    private void BotaoDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDinheiroActionPerformed
        // TODO add your handling code here:
       double dinheiro =jTotal();
       double desc_dinheiro=dinheiro*(0.90);   
       JOptionPane.showMessageDialog(null,"O total em dinheiro é: "+desc_dinheiro+"\nPara pagar clique em 'OK'");
        
    }//GEN-LAST:event_BotaoDinheiroActionPerformed

    private void BotaoDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDebitoActionPerformed
        // TODO add your handling code here:
       double dinheiro =jTotal();
      
       JOptionPane.showMessageDialog(null,"O total em dinheiro é: "+dinheiro+"\nPara prosseguir com o pagamento a conexão com a máquina e necessária.");
    }//GEN-LAST:event_BotaoDebitoActionPerformed

    private void BotaoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCreditoActionPerformed
        // TODO add your handling code here:
        double cartao =jTotal();
        double totalcartao = 0;
        String resposta;
        
        String[] vezes = {  "À vista", "2 vezes", "3 vezes","4 vezes" };

        resposta  = (String)JOptionPane.showInputDialog(null, 
        "Quantas parcelas",
        "Cartão",
        JOptionPane.PLAIN_MESSAGE, 
        null,
        vezes,
        null);
        
        
        
        if (resposta == "À vista") {
            JOptionPane.showMessageDialog(null, "O total a vista é: " + cartao );
            JOptionPane.showMessageDialog(null,"Para prosseguir com o pagamento a conexão com a máquina é necessária.");
        } else if (resposta == "2 vezes") {
            totalcartao = cartao * 1.02;
            JOptionPane.showMessageDialog(null, "O total em 2 vezes  é: " + totalcartao + "\nPara pagar clique em 'OK'");
            JOptionPane.showMessageDialog(null,"Para prosseguir com o pagamento a conexão com a máquina é necessária.");
        } else if (resposta == "3 vezes") {
            totalcartao = cartao * 1.03;
            JOptionPane.showMessageDialog(null, "O total em 3 vezes  é: " + totalcartao + "\nPara pagar clique em 'OK'");
            JOptionPane.showMessageDialog(null,"Para prosseguir com o pagamento a conexão com a máquina é necessária.");
        } else {
            totalcartao = cartao * 1.04;
            JOptionPane.showMessageDialog(null, "O total em 2 vezes  é: " + totalcartao + "\nPara pagar clique em 'OK'");
            JOptionPane.showMessageDialog(null,"Para prosseguir com o pagamento a conexão com a máquina é necessária.");
        }
    }//GEN-LAST:event_BotaoCreditoActionPerformed
    
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
           
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Americano;
    private javax.swing.JButton Batata_Frita_G;
    private javax.swing.JButton Batata_Frita_P;
    private javax.swing.JButton Batata_Frita_c_Cheddar;
    private javax.swing.JButton BotaoCredito;
    private javax.swing.JButton BotaoDebito;
    private javax.swing.JButton BotaoDeletar;
    private javax.swing.JButton BotaoDinheiro;
    private javax.swing.JButton BotaoSetaBaixo;
    private javax.swing.JButton BotaoSetaCima;
    private javax.swing.JButton Chicken_Fries;
    private javax.swing.JButton Filé_Misto;
    private javax.swing.JButton Hambúrguer;
    private javax.swing.JButton Hot_Dog;
    private javax.swing.JButton Refrigerante_Lata250ml;
    private javax.swing.JButton Refrigerante_Lata500ml;
    private javax.swing.JButton Suco;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton X_Burguer;
    private javax.swing.JButton X_Filé;
    private javax.swing.JButton X_Salada;
    private javax.swing.JButton X_Tudo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JButton Água;
    // End of variables declaration//GEN-END:variables

    private void setIcon() { //metodo do icone
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png"))); 
    }

    private double jTotal() {
        return total;
    }
}
